WIP - Add Placement parameter
juju/terraform-provider-juju pull request #378
Opened 2024-01-09 18:39 UTC by amandahla

WIP - DO NOT MERGE

## Description

The machine resource does not support creating machines in LXD/KVM like the following command does:
```
juju add-machine kvm:3
```
This PR adds a placement parameter to provide this option.

Fixes: #347 

## Type of change

- Change existing resource
- Change in tests (one or several tests have been changed)
- Requires a documentation update

## Environment

- Juju controller version: 

- Terraform version: 

## QA steps

Manual QA steps should be done to test this PR.

```tf
provider juju {}
...
```

## Additional notes

N/A

2024-01-30 19:55 UTC, hmlanigan commented
@amandahla run `make docs` and add the updated docs to your PR to resolve the failed workflow.

2024-02-09 19:10 UTC, hmlanigan requested changes
Looks good to start. QA went well with one oddity, including import.

Please rebase this PR and resolve the conflicts. It also needs an acceptance test for this change in resource_machine_test.go

QA oddity. I haven't had a chance to dig. But how this happens isn't obvious:

With this plan part:
```terraform 
resource "juju_model" "testmodel" {
  name = "machinetest"
}

resource "juju_machine" "my-machine-three" {
  model = juju_model.testmodel.name
  placement = ":failme"
}
```

I got:
```
juju_machine.my-machine-three: Creating...
╷
│ Error: Client Error
│
│   with juju_machine.my-machine-three,
│   on heather.tf line 39, in resource "juju_machine" "my-machine-three":
│   39: resource "juju_machine" "my-machine-three" {
│
│ Unable to create machine, got error: invalid model name "model-uuid"
╵
```

2024-02-09 21:45 UTC, hmlanigan commented
@amandahla please do not use merge commits. It's preferable to use `git rebase --pull` instead. Merge commits interfere with the commit history once the PR lands.

2024-03-05 19:52 UTC, amandahla commented
> invalid model name

This error seems to come from [here](https://github.com/juju/juju/blob/55fb5d03683b70dea08d1e54687e0f90bb06a63a/apiserver/facades/client/machinemanager/machinemanager.go#L260).

Reading better now, from what I understood, I need to pass the model-uuid if there is no scope in the directive. Changed and testing now.

2024-03-05 20:24 UTC, amandahla commented
Now the error makes more sense:
```
$ terraform apply
juju_model.development: Refreshing state... [id=51f29c40-4f7e-4c03-8d1a-d10f2b433f01]
juju_machine.this_machine_1: Refreshing state... [id=development:0/lxd/1:this_machine_1]
juju_machine.this_machine: Refreshing state... [id=development:0/lxd/0:this_machine]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # juju_machine.this_machine_2 will be created
  + resource "juju_machine" "this_machine_2" {
      + base       = (known after apply)
      + id         = (known after apply)
      + machine_id = (known after apply)
      + model      = "development"
      + name       = "this_machine_1"
      + placement  = ":fail"
      + series     = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

juju_machine.this_machine_2: Creating...
╷
│ Error: Client Error
│ 
│   with juju_machine.this_machine_2,
│   on main.tf line 28, in resource "juju_machine" "this_machine_2":
│   28: resource "juju_machine" "this_machine_2" {
│ 
│ Unable to create machine, got error: cannot add a new machine: availability zone ":fail" not valid
```

2024-03-06 17:13 UTC, amandahla commented
Fixed the merge/rebase mess.

2024-03-07 20:43 UTC, hmlanigan approved these changes
LGTM! Thank you for your contribution.

2024-03-07 20:43 UTC, merged