Add ClientStore connector support
juju/terraform-provider-juju pull request #423
Opened 2024-03-05 11:01 UTC by phvalguima

## Description

This PR moves away from `SimpleConnector` to `ClientStore`, in sync with remaining juju `modelcmd` commands.

It also adds support for the user to specify the controller name, which changes the schema.

Fixes: 

#421 

## Type of change

- Change existing resource
- Bug fix (non-breaking change which fixes an issue)

## Environment

- Juju controller version: v3.4

- Terraform version: v1.7.4

## QA steps

Manual QA steps should be done to test this PR.

```tf
provider juju {}
...
```

2024-03-05 14:41 UTC, hmlanigan commented
@phvalguima schema changes require separate approval. https://github.com/juju/terraform-provider-juju?tab=readme-ov-file#planning--design When you file a GitHub issue, use the schema change type.  Thank you.

2024-03-06 16:25 UTC, hmlanigan requested changes
There are configs in the wild which do not have access to the controller name and use only IP addresses. GetConnection is used everywhere.  We also need to be careful of juju users without permissions on the controller, e.g. superuser.

We need to investigate why this change works and find a different way to interact with the juju api here which works for all use cases for sure. @cderici might be reaching our from our side for the investigation.

I'm pushing the bug and PR to the 0.12.0 milestone.

2024-03-06 16:37 UTC, phvalguima commented
Hi @hmlanigan okay, no worries.

Agreed, I need to build the `AccountDetails` object. I left unset only because it makes my own testing easier :)

Now, it is not passwordless connection. AFAIU if the user leaves it unset, then it will try to load the details from the Juju CLI. Granted, we may have or not it available. Now, if you have it available, you will also have access to `~/.local/share/juju/` folder of that given user anyways.

2024-03-25 15:26 UTC, hmlanigan commented
Closing this PR. The change appears to work because the client uses the juju store written to the local host. If the client finds a good ip address when connecting, it will write that ip address to the top of the list and continue to use until it doesn't work. Therefore added fan networks won't be tried unless things are going wrong, and this change appears to solve the problem described.

The fan networks will eventually be added by juju in any case. There are configs in the wild which depend on this behavior by juju as well.

2024-03-25 15:26 UTC, closed without merging