Handle race where offer is already destroyed
juju/terraform-provider-juju pull request #446
Opened 2024-04-10 11:14 UTC by jack-w-shaw

## Description

If an offer has already been destroyed, 'DestroyOffer' will fail with a 'not found' error. In this case, there is no offer to destroy, so we should just return successfully.

This race is rare, but has been seen here:
https://github.com/juju/juju/actions/runs/7745564317/job/21121856659?pr=16883

Fixes: https://github.com/juju/terraform-provider-juju/issues/395

## Type of change

- Change existing resource
- Logic changes in resources (the API interaction with Juju has been changed)
- Bug fix (non-breaking change which fixes an issue)
- Maintenance work (repository related, like Github actions, or revving the Go version, etc.)

## Environment

- Juju controller version: I'm using 3.4, since the bug this addresses was seen in 3.4

- Terraform version: 1.7.5

## QA steps

```
TF_ACC="1" TEST_CLOUD="lxd" go test -count=10 -timeout 60m ./internal/provider/ -run TestAcc_ResourceIntegrationWithMultipleConsumers
```

2024-04-10 21:26 UTC, hmlanigan commented
@jack-w-shaw as this is an intermittent failure, more concrete QA steps are necessary.

2024-04-10 21:29 UTC, hmlanigan requested changes
This is an intermittent failure, more concrete QA steps are necessary.

2024-04-10 21:29 UTC, hmlanigan commented on internal/juju/offers.go
> +	if jujuerrors.Is(err, jujuerrors.NotFound) {
We don't get actual types out of the juju clients usually. Check out some of the other NotFound code.

2024-05-01 15:06 UTC, closed without merging

2024-08-08 11:37 UTC, gtato commented
This is not really rare. It happens all the time. 
My plan looks more or less like this: https://git.launchpad.net/~yellow/canonical-terraform-plans/+git/canonical-terraform-plans/tree/data-warehouse/modules/data-warehouse/main.tf?h=new-data-warehouse

I am not sure if the fact that I am creating them in a loop has smth to do with it, or the fact that this plan takes quite some time to destroy.